### ISSUE TITLE
Fix TransactionalProducer implementation once Confluent driver support this

### ISSUE THREAD

**Issue by IgorFedchenko** [akkadotnet/Akka.Streams.Kafka#85]
There are couple of `TODO` labels in `TransactionalProducerStage.cs` file (in `TransactionalProducerStageLogic` class implementation). This is due to lack of transactional operations support in Confluent driver's producer implementation. 

This also requires some `librdkafka` update. The issue to track is https://github.com/confluentinc/confluent-kafka-dotnet/issues/1091.

Once this will be ready, implementation should work (there is a test  at `TransactionalIntegrationTests.cs` that is skipped right now).

**Comment by IgorFedchenko** [comment]
Looks like they have published update which includes transaction support: https://www.nuget.org/packages/Confluent.Kafka/1.4.0

So now we can implement missing transactional stages.

**Comment by chris-sung** [comment]
ah, this is a long waiting feature that I'm waiting to be implemented

**Comment by IgorFedchenko** [comment]
@chris-sung Yeah, the problem is that `_producer.InitTransactions` call to Confluent driver is blocking for some reason, and I can't make my PR passing tests. And I ran out of time, not able to fix it now... If you will have time and willing to check it out or fork my branch and play with this, you are wellcome :)

Otherwise it may take a long time to have this working...

**Comment by rafalpiotrowski** [comment]
Hi, Is this resolved now? or still pending?

**Comment by IgorFedchenko** [comment]
Hey, nope, this is not resolved - there is a PR (https://github.com/akkadotnet/Akka.Streams.Kafka/pull/196) which was never finished (see comments above). Probably it will work now with latest driver versions, not sure.
